### ISSUE TITLE
Error on build in VS.NET 2013

### ISSUE THREAD

**Issue by scromer** [shawty/polymermvc#1]
I tried running this in 2013 and upon initial build and run I got this error.

Server Error in '/' Application.

Could not load file or assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Source Error: 

Line 2:  {
Line 3:    @nav.Header("Main Menu")
Line 4:    @nav.ActionLink("Home", "Index", "Home")
Line 5:    @nav.ActionLink("Graph", "Graph", "Home")
Line 6:    @nav.Divider()

**Comment by shawty** [comment]
Hi Scromer,

The error presented would suggest that you don't have asp.net MVC V3 installed in your development environment.

Not entirely sure why that would cause a problem, beacuse as is things build entirely fine for me under VS2013 Ultimate, and also under VS2012 where the project was first created.

As for the polymer project itself, it's written to use MVC4 so should not actually need or be looking for MVC3.

All I can suggest is to try installing the MVC3 toolkit and see if that solves your problem.

Cheers
Shawty

**Comment by scromer** [comment]
Thanks peter. What is your initial impression of polymer?

**Comment by shawty** [comment]
I think it's absolutely great.  Still has some maturing to do, but Google have had it in their Dart Language for quite sometime now.

The one place I've found that it's #WIN all the way is in porting between environments.  I work a lot between .NET & PHP and others, and being able to build a component once and use it in multiple places without alteration is fantastic.

btw: I do have an update ready(ish) to push to this repo and update my sample, I've figured out a slightly better way of restructuring things.  As it stands if you run the app off a leaf folder from the url root, you'll have problems making the various parts of Polymer find each other.

I'll get the update pushed asap

**Comment by scromer** [comment]
Awesome thanks! I'm a long time .net developer that is just getting into angular and polymer so I'm excited about all of this any direction I can get would be great. 

Thanks for your help!
Sam

**Comment by shawty** [comment]
Not a problem Sam.

Why don't you hop across to Lidnug (I help run the User group) start a discussion there.

Then we can close this issue :-)

You can get to Lidnug at : http://www.linkedin.com/groups/LinkedNET-Users-Group-LIDNUG-43315

**Comment by scromer** [comment]
Will do thanks!
